# Generated by Django 4.2.7 on 2025-12-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pattern_description',
        ),
        migrations.AddField(
            model_name='product',
            name='custom_pattern',
            field=models.CharField(blank=True, help_text='Enter custom pattern name', max_length=100),
        ),
    ]
