# Generated by Django 4.2.7 on 2026-01-08 06:07

from django.db import migrations


def migrate_custom_pattern_to_category(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Category = apps.get_model('products', 'Category')
    
    # Get all categories for lookup
    categories = {cat.name: cat for cat in Category.objects.all()}
    
    # Process products with custom patterns
    products_to_delete = []
    products_to_update = []
    
    for product in Product.objects.filter(pattern='custom'):
        custom_pattern = product.custom_pattern.strip()
        
        # Check if custom_pattern matches any category name
        if custom_pattern in categories:
            # Link product to category
            products_to_update.append(product)
        else:
            # Mark for deletion - no matching category
            products_to_delete.append(product)
    
    # Update products with matching categories
    for product in products_to_update:
        custom_pattern = product.custom_pattern.strip()
        product.category = categories[custom_pattern]
        product.save(update_fields=['category'])
    
    # Delete products with no matching category
    if products_to_delete:
        product_ids = [p.id for p in products_to_delete]
        Product.objects.filter(id__in=product_ids).delete()
        print(f"Deleted {len(products_to_delete)} products with no matching category")


def reverse_migrate_custom_pattern_to_category(apps, schema_editor):
    # This migration is not reversible due to data deletion
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_add_category_field"),
    ]

    operations = [
        migrations.RunPython(
            migrate_custom_pattern_to_category,
            reverse_migrate_custom_pattern_to_category,
        ),
    ]
