# Generated by Django 4.2.7 on 2026-01-08 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_migrate_custom_pattern_to_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="custom_pattern",
        ),
    ]
